# roles/caddy/handlers/main.yml

- name: restart caddy
  command: docker compose restart caddy
  args:
    chdir: "{{ matrix_base_dir }}"
  become_user: "{{ admin_user }}"

- name: restart synapse-admin
  command: docker compose restart synapse-admin
  args:
    chdir: "{{ matrix_base_dir }}"
  become_user: "{{ admin_user }}"

- name: restart caddy-admin
  command: docker compose restart caddy-admin
  args:
    chdir: "{{ matrix_base_dir }}"
  become_user: "{{ admin_user }}"
